# :include customizedComponents.kv

<BoundaryConditionLayout>
    orientation: "vertical"
    canvas.before:    
        Color:
            rgba: 252/255.0, 251/255.0, 244/255.0, 1  # Background color for the layout
        Rectangle:
            pos: self.pos
            size: self.size 

    # This GridLayout is used to contain below info:
    # 1. nbc: number of Boundary
    # 2. Add Button
    # 3. Delete Button    
    GridLayout:
        size_hint_y: 0.05    
        cols: 4
        row_force_default: True
        row_default_height: 50
        col_force_default: True
        col_default_width: 260
        spacing: 10
        padding: 20

        # row 1: nbc 
        BlackLabel:    
            text: "nbc:"
        BlackLabel:
            id: nbc-    
            text: "1"
        MyButton:
            text: "Add"
            on_release: root.addOneMoreEntry()
        MyButton:
            text: "Delete"  
            on_release: root.deleteOneBdryEntry()

    # This GridLayout is used to contain the header for bdry_name entries table
    GridLayout:
        size_hint_y: 0.05    
        cols: 4
        row_force_default: True
        row_default_height: 50
        col_force_default: True
        col_default_width: 260
        spacing: 10
        padding: 20

        # row 2: entries header
        Label:
        BlackLabel:
            text: "seq"
            halign: "right"
        BlackLabel:
            text: "bdnum"
            halign: "right"
        BlackLabel:
            text: "name"
            halign: "right"         
    
    # This BoxLayout contains a scrollview that is used to display the bdry_name entries table
    BoxLayout:
        size_hint_y: 0.4
        ScrollView:
            orientation: "vertical"
            do_scroll_y: True
            do_scroll_x: False
            GridLayout:
                # Add below three lines to ensure that the scrollView which contains this BoundaryConditionLayout works.
                height: self.minimum_height
                # width: self.minimum_width
                # size_hint: None, None
                size_hint_y: None

                id: bdry_nameGridLayout   
                cols: 4
                row_force_default: True
                row_default_height: 50
                col_force_default: True
                col_default_width: 260
                spacing: 10
                padding: 20
                #row 1
                BlackLabel:
                    text: "bdry_name"
                    id: bdry_name-1
                BlackLabel:
                    text: "1"
                    halign: "right"
                    id: bdry_nameSeqLabel-1
                TextInput:
                    text: ""
                    multiline: False  
                    id: bdry_nameBdnumTextInput-1  
                TextInput:
                    text: ""
                    multiline: False
                    id: nameTextInput-1

    GridLayout:
        size_hint_y: 0.05    
        cols: 12 
        row_force_default: True
        row_default_height: 50
        col_force_default: True
        col_default_width: 150 
        spacing: 10
        padding: 20

        # row 2: entries header
        Label:
        BlackLabel:
            text: "seq"
            halign: "right"
    
        BlackLabel:
            text: "bc-sc"
            halign: "right"
        BlackLabel:
            text: "bc-sc"
            halign: "right"
        BlackLabel:
            text: "bc-p"
            halign: "right"
        BlackLabel:
            text: "bc-p"
            halign: "right"
        
        
    
    BoxLayout:
        size_hint_y: 0.35
        ScrollView:
            # orientation: "vertical"
            do_scroll_y: True
            do_scroll_x: True 
            GridLayout:
                # Add below two lines to ensure that the scrollView which contains this BoundaryConditionLayout works.
                height: self.minimum_height
                size_hint_y: None    

                id: bcGridLayout
                cols: 6
                row_force_default: True
                row_default_height: 50
                col_force_default: True
                col_default_width: 150
                spacing: 10
                padding: 20

                BlackLabel:
                    text: "bc"
                    id: bc-1
                BlackLabel:
                    text: "1"
                    halign: "right"
                    id: bc-seq-1
                TextInput:
                    text: ""
                    multiline: False   
                    id: bc-sc1-1 
                TextInput:
                    text: ""
                    multiline: False
                    id: bc-sc2-1
                TextInput:
                    text: ""
                    multiline: False
                    id: bc-p1-1    
                TextInput:
                    text: ""
                    multiline: False
                    id: bc-p2-1
                